using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Collections.Generic;


namespace CapstoneCCPCompany.Function
{
    public class MyObject
    {
        // public int Id { get; set; }
        // public string Name { get; set; }
        public string customer_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; } 
    }
    public static class HttpTrigger1
    {
        [FunctionName("HttpTrigger1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            List<MyObject> myObjects = new List<MyObject>
            {
                // new MyObject { Id = 1,  Name = "Object A" "}, 
                // new MyObject { Id = 2,  Name = "Object B" }
                new MyObject{customer_id= "customer_id", first_name= "first_name", last_name= "last_name", phone= "phone", email= "email", street= "street", city= "city", state= "state", zip_code= "zip_code"}, 
                new MyObject{customer_id= "1", first_name= "Debra", last_name= "Burks", phone= "NULL", email= "debra.burks@yahoo.com", street= "9273 Thorne Ave.", city= "Orchard Park", state= "NY", zip_code= "14127"}, 
                new MyObject{customer_id= "2", first_name= "Kasha", last_name= "Todd", phone= "NULL", email= "kasha.todd@yahoo.com", street= "910 Vine Street", city= "Campbell", state= "CA", zip_code= "95008"}, 
                new MyObject{ customer_id= "3", first_name= "Tameka",  last_name= "Fisher",  phone= "NULL",  email= "tameka.fisher@aol.com",  street= "769C Honey Creek St.",  city= "Redondo Beach",  state= "CA",  zip_code= "90278 "}, 
                new MyObject{ customer_id= "4", first_name= "Daryl",  last_name= "Spence",  phone= "NULL",  email= "daryl.spence@aol.com",  street= "988 Pearl Lane",  city= "Uniondale",  state= "NY",  zip_code= "11553 "},  
                new MyObject{ customer_id= "5", first_name= "Charolette",  last_name= "Rice",  phone= "(916) 381-6003",  email= "charolette.rice@msn.com",  street= "107 River Dr.",  city= "Sacramento",  state= "CA",  zip_code= "95820 "},  
                new MyObject{ customer_id= "6", first_name= "Lyndsey",  last_name= "Bean",  phone= "NULL",  email= "lyndsey.bean@hotmail.com",  street= "769 West Road",  city= "Fairport",  state= "NY",  zip_code= "14450 "},  
                new MyObject{ customer_id= "7", first_name= "Latasha",  last_name= "Hays",  phone= "(716) 986-3359",  email= "latasha.hays@hotmail.com",  street= "7014 Manor Station Rd.",  city= "Buffalo",  state= "NY",  zip_code= "14215 "},  
                new MyObject{ customer_id= "8", first_name= "Jacquline",  last_name= "Duncan",  phone= "NULL",  email= "jacquline.duncan@yahoo.com",  street= "15 Brown St.",  city= "Jackson Heights",  state= "NY",  zip_code= "11372 "},  
                new MyObject{ customer_id= "9", first_name= "Genoveva",  last_name= "Baldwin",  phone= "NULL",  email= "genoveva.baldwin@msn.com",  street= "8550 Spruce Drive",  city= "Port Washington",  state= "NY",  zip_code= "11050 "},  
                new MyObject{ customer_id= "10", first_name= "Pamelia",  last_name= "Newman",  phone= "NULL",  email= "pamelia.newman@gmail.com",  street= "476 Chestnut Ave.",  city= "Monroe",  state= "NY",  zip_code= "10950 "},  
                new MyObject{ customer_id= "11", first_name= "Deshawn",  last_name= "Mendoza",  phone= "NULL",  email= "deshawn.mendoza@yahoo.com",  street= "8790 Cobblestone Street",  city= "Monsey",  state= "NY",  zip_code= "10952 "},  
                new MyObject{ customer_id= "12", first_name= "Robby",  last_name= "Sykes",  phone= "(516) 583-7761",  email= "robby.sykes@hotmail.com",  street= "486 Rock Maple Street",  city= "Hempstead",  state= "NY",  zip_code= "11550 "},  
                new MyObject{ customer_id= "13", first_name= "Lashawn",  last_name= "Ortiz",  phone= "NULL",  email= "lashawn.ortiz@msn.com",  street= "27 Washington Rd.",  city= "Longview",  state= "TX",  zip_code= "75604 "},  
                new MyObject{ customer_id= "14", first_name= "Garry",  last_name= "Espinoza",  phone= "NULL",  email= "garry.espinoza@hotmail.com",  street= "7858 Rockaway Court",  city= "Forney",  state= "TX",  zip_code= "75126 "},  
                new MyObject{ customer_id= "15", first_name= "Linnie",  last_name= "Branch",  phone= "NULL",  email= "linnie.branch@gmail.com",  street= "314 South Columbia Ave.",  city= "Plattsburgh",  state= "NY",  zip_code= "12901 "},  
                new MyObject{ customer_id= "16", first_name= "Emmitt",  last_name= "Sanchez",  phone= "(212) 945-8823",  email= "emmitt.sanchez@hotmail.com",  street= "461 Squaw Creek Road",  city= "New York",  state= "NY",  zip_code= "10002 "},  
                new MyObject{ customer_id= "17", first_name= "Caren",  last_name= "Stephens",  phone= "NULL",  email= "caren.stephens@msn.com",  street= "914 Brook St.",  city= "Scarsdale",  state= "NY",  zip_code= "10583 "},  
                new MyObject{ customer_id= "18", first_name= "Georgetta",  last_name= "Hardin",  phone= "NULL",  email= "georgetta.hardin@aol.com",  street= "474 Chapel Dr.",  city= "Canandaigua",  state= "NY",  zip_code= "14424 "},  
                new MyObject{ customer_id= "19", first_name= "Lizzette",  last_name= "Stein",  phone= "NULL",  email= "lizzette.stein@yahoo.com",  street= "19 Green Hill Lane",  city= "Orchard Park",  state= "NY",  zip_code= "14127 "},  
                new MyObject{ customer_id= "20", first_name= "Aleta",  last_name= "Shepard",  phone= "NULL",  email= "aleta.shepard@aol.com",  street= "684 Howard St.",  city= "Sugar Land",  state= "TX",  zip_code= "77478 "},  
                new MyObject{ customer_id= "21", first_name= "Tobie",  last_name= "Little",  phone= "NULL",  email= "tobie.little@gmail.com",  street= "10 Silver Spear Dr.",  city= "Victoria",  state= "TX",  zip_code= "77904 "},  
                new MyObject{ customer_id= "22", first_name= "Adelle",  last_name= "Larsen",  phone= "NULL",  email= "adelle.larsen@gmail.com",  street= "683 West Kirkland Dr.",  city= "East Northport",  state= "NY",  zip_code= "11731 "},  
                new MyObject{ customer_id= "23", first_name= "Kaylee",  last_name= "English",  phone= "NULL",  email= "kaylee.english@msn.com",  street= "8786 Fulton Rd.",  city= "Hollis",  state= "NY",  zip_code= "11423 "},  
                new MyObject{ customer_id= "24", first_name= "Corene",  last_name= "Wall",  phone= "NULL",  email= "corene.wall@msn.com",  street= "9601 Ocean Rd.",  city= "Atwater",  state= "CA",  zip_code= "95301 "},  
                new MyObject{ customer_id= "25", first_name= "Regenia",  last_name= "Vaughan",  phone= "NULL",  email= "regenia.vaughan@gmail.com",  street= "44 Stonybrook Street",  city= "Mahopac",  state= "NY",  zip_code= "10541 "},  
                new MyObject{ customer_id= "26", first_name= "Theo",  last_name= "Reese",  phone= "(562) 215-2907",  email= "theo.reese@gmail.com",  street= "8755 W. Wild Horse St.",  city= "Long Beach",  state= "NY",  zip_code= "11561 "},  
                new MyObject{ customer_id= "27", first_name= "Santos",  last_name= "Valencia",  phone= "NULL",  email= "santos.valencia@yahoo.com",  street= "7479 Carpenter Street",  city= "Sunnyside",  state= "NY",  zip_code= "11104 "},  
                new MyObject{ customer_id= "28", first_name= "Jeanice",  last_name= "Frost",  phone= "NULL",  email= "jeanice.frost@hotmail.com",  street= "76 Devon Lane",  city= "Ossining",  state= "NY",  zip_code= "10562 "},  
                new MyObject{ customer_id= "29", first_name= "Syreeta",  last_name= "Hendricks",  phone= "NULL",  email= "syreeta.hendricks@msn.com",  street= "193 Spruce Road",  city= "Mahopac",  state= "NY",  zip_code= "10541 "},  
                new MyObject{ customer_id= "30", first_name= "Jamaal",  last_name= "Albert",  phone= "NULL",  email= "jamaal.albert@gmail.com",  street= "853 Stonybrook Street",  city= "Torrance",  state= "CA",  zip_code= "90505 "},  
                new MyObject{ customer_id= "31", first_name= "Williemae",  last_name= "Holloway",  phone= "(510) 246-8375",  email= "williemae.holloway@msn.com",  street= "69 Cypress St.",  city= "Oakland",  state= "CA",  zip_code= "94603 "},  
                new MyObject{ customer_id= "32", first_name= "Araceli",  last_name= "Golden",  phone= "NULL",  email= "araceli.golden@msn.com",  street= "12 Ridgeview Ave.",  city= "Fullerton",  state= "CA",  zip_code= "92831 "},  
                new MyObject{ customer_id= "33", first_name= "Deloris",  last_name= "Burke",  phone= "NULL",  email= "deloris.burke@hotmail.com",  street= "895 Edgemont Drive",  city= "Palos Verdes Peninsula",  state= "CA",  zip_code= "90274 "},  
                new MyObject{ customer_id= "34", first_name= "Brittney",  last_name= "Woodward",  phone= "NULL",  email= "brittney.woodward@aol.com",  street= "960 River St.",  city= "East Northport",  state= "NY",  zip_code= "11731 "},  
                new MyObject{ customer_id= "35", first_name= "Guillermina",  last_name= "Noble",  phone= "NULL",  email= "guillermina.noble@msn.com",  street= "6 Del Monte Lane",  city= "Baldwinsville",  state= "NY",  zip_code= "13027 "},  
                new MyObject{ customer_id= "36", first_name= "Bernita",  last_name= "Mcdaniel",  phone= "NULL",  email= "bernita.mcdaniel@hotmail.com",  street= "2 Peg Shop Ave.",  city= "Liverpool",  state= "NY",  zip_code= "13090 "},  
                new MyObject{ customer_id= "37", first_name= "Melia",  last_name= "Brady",  phone= "NULL",  email= "melia.brady@gmail.com",  street= "907 Shirley Rd.",  city= "Maspeth",  state= "NY",  zip_code= "11378 "},  
                new MyObject{ customer_id= "38", first_name= "Zelma",  last_name= "Browning",  phone= "NULL",  email= "zelma.browning@aol.com",  street= "296 Second Street",  city= "Astoria",  state= "NY",  zip_code= "11102 "},  
                new MyObject{ customer_id= "39", first_name= "Janetta",  last_name= "Aguirre",  phone= "(717) 670-2634",  email= "janetta.aguirre@aol.com",  street= "214 Second Court",  city= "Lancaster",  state= "NY",  zip_code= "14086 "},  
                new MyObject{ customer_id= "40", first_name= "Ronna",  last_name= "Butler",  phone= "NULL",  email= "ronna.butler@gmail.com",  street= "9438 Plymouth Court",  city= "Encino",  state= "CA",  zip_code= "91316 "},  
                new MyObject{ customer_id= "41", first_name= "Kathie",  last_name= "Freeman",  phone= "NULL",  email= "kathie.freeman@msn.com",  street= "667 Temple Dr.",  city= "Queensbury",  state= "NY",  zip_code= "12804 "},  
                new MyObject{ customer_id= "42", first_name= "Tangela",  last_name= "Quinn",  phone= "NULL",  email= "tangela.quinn@aol.com",  street= "4 S. Purple Finch Road",  city= "Richmond Hill",  state= "NY",  zip_code= "11418 "},  
                new MyObject{ customer_id= "43", first_name= "Mozelle",  last_name= "Carter",  phone= "(281) 489-9656",  email= "mozelle.carter@aol.com",  street= "895 Chestnut Ave.",  city= "Houston",  state= "TX",  zip_code= "77016 "},  
                new MyObject{ customer_id= "44", first_name= "Onita",  last_name= "Johns",  phone= "NULL",  email= "onita.johns@msn.com",  street= "32 Glen Creek Lane",  city= "Elmont",  state= "NY",  zip_code= "11003 "},  
                new MyObject{ customer_id= "45", first_name= "Bennett",  last_name= "Armstrong",  phone= "NULL",  email= "bennett.armstrong@aol.com",  street= "688 Walnut Street",  city= "Bethpage",  state= "NY",  zip_code= "11714 "},  
                new MyObject{ customer_id= "46", first_name= "Monika",  last_name= "Berg",  phone= "NULL",  email= "monika.berg@gmail.com",  street= "369 Vernon Dr.",  city= "Encino",  state= "CA",  zip_code= "91316 "},  
                new MyObject{ customer_id= "47", first_name= "Bridgette",  last_name= "Guerra",  phone= "NULL",  email= "bridgette.guerra@hotmail.com",  street= "9982 Manor Drive",  city= "San Lorenzo",  state= "CA",  zip_code= "94580 "},  
                new MyObject{ customer_id= "48", first_name= "Cesar",  last_name= "Jackson",  phone= "NULL",  email= "cesar.jackson@gmail.com",  street= "8068 N. Griffin Ave.",  city= "Liverpool",  state= "NY",  zip_code= "13090 "},  
                new MyObject{ customer_id= "49", first_name= "Caroll",  last_name= "Hays",  phone= "NULL",  email= "caroll.hays@yahoo.com",  street= "9381 Wrangler St.",  city= "Fairport",  state= "NY",  zip_code= "14450 "},  
                new MyObject{ customer_id= "50", first_name= "Cleotilde",  last_name= "Booth",  phone= "NULL",  email= "cleotilde.booth@gmail.com",  street= "17 Corona St.",  city= "Sugar Land",  state= "TX",  zip_code= "77478 "},  
                new MyObject{ customer_id= "51", first_name= "Gertrud",  last_name= "Rhodes",  phone= "NULL",  email= "gertrud.rhodes@aol.com",  street= "9961 Meadowbrook Street",  city= "Merrick",  state= "NY",  zip_code= "11566 "},  
                new MyObject{ customer_id= "52", first_name= "Tu",  last_name= "Ramirez",  phone= "NULL",  email= "tu.ramirez@hotmail.com",  street= "24 W. Courtland Street",  city= "East Elmhurst",  state= "NY",  zip_code= "11369 "},  
                new MyObject{ customer_id= "53", first_name= "Saturnina",  last_name= "Garner",  phone= "NULL",  email= "saturnina.garner@gmail.com",  street= "8538 Fairground St.",  city= "Glendora",  state= "CA",  zip_code= "91740 "},  
                new MyObject{ customer_id= "54", first_name= "Fran",  last_name= "Yang",  phone= "NULL",  email= "fran.yang@hotmail.com",  street= "440 Pearl St.",  city= "Utica",  state= "NY",  zip_code= "13501 "},  
                new MyObject{ customer_id= "55", first_name= "Diana",  last_name= "Guerra",  phone= "NULL",  email= "diana.guerra@hotmail.com",  street= "45 Chapel Ave.",  city= "Merrick",  state= "NY",  zip_code= "11566 "},  
                new MyObject{ customer_id= "56", first_name= "Lolita",  last_name= "Mosley",  phone= "(281) 363-3309",  email= "lolita.mosley@hotmail.com",  street= "376 S. High Ridge St.",  city= "Houston",  state= "TX",  zip_code= "77016 "},  
                new MyObject{ customer_id= "57", first_name= "Pamala",  last_name= "Henry",  phone= "NULL",  email= "pamala.henry@aol.com",  street= "197 Bridgeton Ave.",  city= "Bronx",  state= "NY",  zip_code= "10451 "},  
                new MyObject{ customer_id= "58", first_name= "Damien",  last_name= "Dorsey",  phone= "NULL",  email= "damien.dorsey@yahoo.com",  street= "161 Old York Street",  city= "Central Islip",  state= "NY",  zip_code= "11722 "},  
                new MyObject{ customer_id= "59", first_name= "Latasha",  last_name= "Stanley",  phone= "NULL",  email= "latasha.stanley@gmail.com",  street= "8068 Fordham Drive",  city= "Rockville Centre",  state= "NY",  zip_code= "11570 "},  
                new MyObject{ customer_id= "60", first_name= "Neil",  last_name= "Mccall",  phone= "NULL",  email= "neil.mccall@gmail.com",  street= "7476 Oakland Dr.",  city= "San Carlos",  state= "CA",  zip_code= "94070 "},  
                new MyObject{ customer_id= "61", first_name= "Elinore",  last_name= "Aguilar",  phone= "NULL",  email= "elinore.aguilar@msn.com",  street= "9766 Rockcrest Ave.",  city= "San Angelo",  state= "TX",  zip_code= "76901 "},  
                new MyObject{ customer_id= "62", first_name= "Alica",  last_name= "Hunter",  phone= "NULL",  email= "alica.hunter@hotmail.com",  street= "8 San Juan Drive",  city= "East Elmhurst",  state= "NY",  zip_code= "11369 "},  
                new MyObject{ customer_id= "63", first_name= "Tenisha",  last_name= "Lyons",  phone= "NULL",  email= "tenisha.lyons@aol.com",  street= "78 E. Rock Creek Street",  city= "Amityville",  state= "NY",  zip_code= "11701 "},  
                new MyObject{ customer_id= "64", first_name= "Bobbie",  last_name= "Foster",  phone= "NULL",  email= "bobbie.foster@yahoo.com",  street= "988 Pineknoll Ave.",  city= "Desoto",  state= "TX",  zip_code= "75115 "},  
                new MyObject{ customer_id= "65", first_name= "Kanesha",  last_name= "Vega",  phone= "NULL",  email= "kanesha.vega@gmail.com",  street= "771 E. Oxford Drive",  city= "Rome",  state= "NY",  zip_code= "13440 "},  
                new MyObject{ customer_id= "66", first_name= "Lorrie",  last_name= "Becker",  phone= "NULL",  email= "lorrie.becker@yahoo.com",  street= "19 North Court",  city= "Garland",  state= "TX",  zip_code= "75043 "},  
                new MyObject{ customer_id= "67", first_name= "Tommie",  last_name= "Melton",  phone= "(916) 802-2952",  email= "tommie.melton@gmail.com",  street= "8 West Old York St.",  city= "Sacramento",  state= "CA",  zip_code= "95820 "},  
                new MyObject{ customer_id= "68", first_name= "Jayne",  last_name= "Kirkland",  phone= "NULL",  email= "jayne.kirkland@hotmail.com",  street= "7800 Second Lane",  city= "Rowlett",  state= "TX",  zip_code= "75088 "},  
                new MyObject{ customer_id= "69", first_name= "Katelin",  last_name= "Kennedy",  phone= "NULL",  email= "katelin.kennedy@gmail.com",  street= "286 Myrtle Lane",  city= "Rocklin",  state= "CA",  zip_code= "95677 "},  
                new MyObject{ customer_id= "70", first_name= "Tomasa",  last_name= "Carson",  phone= "NULL",  email= "tomasa.carson@aol.com",  street= "10 Clark Avenue",  city= "East Elmhurst",  state= "NY",  zip_code= "11369 "},  
                new MyObject{ customer_id= "71", first_name= "Takako",  last_name= "Casey",  phone= "NULL",  email= "takako.casey@aol.com",  street= "7548 Court Lane",  city= "Bronx",  state= "NY",  zip_code= "10451 "},  
                new MyObject{ customer_id= "72", first_name= "Petronila",  last_name= "Norris",  phone= "NULL",  email= "petronila.norris@aol.com",  street= "72 South Marshall Lane",  city= "South El Monte",  state= "CA",  zip_code= "91733 "},  
                new MyObject{ customer_id= "73", first_name= "Melanie",  last_name= "Hayes",  phone= "NULL",  email= "melanie.hayes@msn.com",  street= "5 N. Hall Dr.",  city= "Liverpool",  state= "NY",  zip_code= "13090 "},  
                new MyObject{ customer_id= "74", first_name= "Georgeann",  last_name= "Waller",  phone= "NULL",  email= "georgeann.waller@yahoo.com",  street= "9797 Bald Hill Ave.",  city= "North Tonawanda",  state= "NY",  zip_code= "14120 "},  
                new MyObject{ customer_id= "75", first_name= "Abby",  last_name= "Gamble",  phone= "NULL",  email= "abby.gamble@aol.com",  street= "60 Myers Dr.",  city= "Amityville",  state= "NY",  zip_code= "11701 "},  
                new MyObject{ customer_id= "76", first_name= "Parker",  last_name= "Prince",  phone= "NULL",  email= "parker.prince@hotmail.com",  street= "21 Sulphur Springs Drive",  city= "Port Jefferson Station",  state= "NY",  zip_code= "11776 "},  
                new MyObject{ customer_id= "77", first_name= "Keri",  last_name= "Bridges",  phone= "NULL",  email= "keri.bridges@gmail.com",  street= "8504 Brickell Ave.",  city= "Richardson",  state= "TX",  zip_code= "75080 "},  
                new MyObject{ customer_id= "78", first_name= "Chi",  last_name= "Goff",  phone= "NULL",  email= "chi.goff@aol.com",  street= "3 W. Glen Ridge Avenue",  city= "Palos Verdes Peninsula",  state= "CA",  zip_code= "90274 "},  
                new MyObject{ customer_id= "79", first_name= "Ashanti",  last_name= "Parks",  phone= "NULL",  email= "ashanti.parks@hotmail.com",  street= "846 N. Helen St.",  city= "Baldwin",  state= "NY",  zip_code= "11510 "},  
                new MyObject{ customer_id= "80", first_name= "Sarai",  last_name= "Mckee",  phone= "(716) 912-8110",  email= "sarai.mckee@msn.com",  street= "641 Glenwood Avenue",  city= "Buffalo",  state= "NY",  zip_code= "14215 "},  
                new MyObject{ customer_id= "81", first_name= "Zina",  last_name= "Bonner",  phone= "NULL",  email= "zina.bonner@hotmail.com",  street= "9312 8th Street",  city= "San Lorenzo",  state= "CA",  zip_code= "94580 "},  
                new MyObject{ customer_id= "82", first_name= "Lizzie",  last_name= "Joyner",  phone= "NULL",  email= "lizzie.joyner@msn.com",  street= "8541 Roberts St.",  city= "Coachella",  state= "CA",  zip_code= "92236 "},  
                new MyObject{ customer_id= "83", first_name= "Tiesha",  last_name= "Daniel",  phone= "NULL",  email= "tiesha.daniel@yahoo.com",  street= "6 West Bohemia Lane",  city= "Scarsdale",  state= "NY",  zip_code= "10583 "},  
                new MyObject{ customer_id= "84", first_name= "Armand",  last_name= "Whitehead",  phone= "NULL",  email= "armand.whitehead@hotmail.com",  street= "639 Harvey St.",  city= "Lindenhurst",  state= "NY",  zip_code= "11757 "},  
                new MyObject{ customer_id= "85", first_name= "Teofila",  last_name= "Fischer",  phone= "NULL",  email= "teofila.fischer@aol.com",  street= "1 West Brickyard St.",  city= "Huntington Station",  state= "NY",  zip_code= "11746 "},  
                new MyObject{ customer_id= "86", first_name= "Lissa",  last_name= "Vargas",  phone= "NULL",  email= "lissa.vargas@yahoo.com",  street= "517 Victoria Ave.",  city= "Oswego",  state= "NY",  zip_code= "13126 "},  
                new MyObject{ customer_id= "87", first_name= "Yan",  last_name= "Mcgowan",  phone= "NULL",  email= "yan.mcgowan@msn.com",  street= "8960 Newport Ave.",  city= "Duarte",  state= "CA",  zip_code= "91010 "},  
                new MyObject{ customer_id= "88", first_name= "Titus",  last_name= "Bullock",  phone= "NULL",  email= "titus.bullock@gmail.com",  street= "29 Oxford Avenue",  city= "Hollis",  state= "NY",  zip_code= "11423 "},  
                new MyObject{ customer_id= "89", first_name= "Arvilla",  last_name= "Osborn",  phone= "NULL",  email= "arvilla.osborn@gmail.com",  street= "60 Acacia Lane",  city= "Upland",  state= "CA",  zip_code= "91784 "},  
                new MyObject{ customer_id= "90", first_name= "Marjorie",  last_name= "Logan",  phone= "NULL",  email= "marjorie.logan@msn.com",  street= "95 Grandrose St.",  city= "Franklin Square",  state= "NY",  zip_code= "11010 "},  
                new MyObject{ customer_id= "91", first_name= "Marvin",  last_name= "Mullins",  phone= "(619) 635-2027",  email= "marvin.mullins@aol.com",  street= "7489 Redwood Drive",  city= "San Diego",  state= "CA",  zip_code= "92111 "},  
                new MyObject{ customer_id= "92", first_name= "Tena",  last_name= "Cruz",  phone= "NULL",  email= "tena.cruz@yahoo.com",  street= "1 South St.",  city= "Farmingdale",  state= "NY",  zip_code= "11735 "},  
                new MyObject{ customer_id= "93", first_name= "Corrina",  last_name= "Sawyer",  phone= "(248) 370-1364",  email= "corrina.sawyer@yahoo.com",  street= "95 Briarwood Lane",  city= "Troy",  state= "NY",  zip_code= "12180 "},  
                new MyObject{ customer_id= "94", first_name= "Sharyn",  last_name= "Hopkins",  phone= "NULL",  email= "sharyn.hopkins@hotmail.com",  street= "4 South Temple Ave.",  city= "Baldwinsville",  state= "NY",  zip_code= "13027 "},  
                new MyObject{ customer_id= "95", first_name= "Letitia",  last_name= "Franco",  phone= "NULL",  email= "letitia.franco@aol.com",  street= "607 Lakeview Drive",  city= "Saratoga Springs",  state= "NY",  zip_code= "12866 "},  
                new MyObject{ customer_id= "96", first_name= "Floretta",  last_name= "Higgins",  phone= "NULL",  email= "floretta.higgins@hotmail.com",  street= "870 Lilac Dr.",  city= "Bayside",  state= "NY",  zip_code= "11361 "},  
                new MyObject{ customer_id= "97", first_name= "Louanne",  last_name= "Martin",  phone= "NULL",  email= "louanne.martin@hotmail.com",  street= "1 Campfire Ave.",  city= "Yuba City",  state= "CA",  zip_code= "95993 "},  
                new MyObject{ customer_id= "98", first_name= "Violet",  last_name= "Valenzuela",  phone= "NULL",  email= "violet.valenzuela@msn.com",  street= "8668 Piper Street",  city= "Plattsburgh",  state= "NY",  zip_code= "12901 "},  
                new MyObject{ customer_id= "99", first_name= "Carie",  last_name= "Kidd",  phone= "NULL",  email= "carie.kidd@yahoo.com",  street= "6 East Clinton Street",  city= "Monroe",  state= "NY",  zip_code= "10950 "},  
                new MyObject{ customer_id= "100", first_name= "Kellie",  last_name= "Franco",  phone= "NULL",  email= "kellie.franco@yahoo.com",  street= "444 South Walnut Rd.",  city= "Commack",  state= "NY",  zip_code= "11725 "},  
                new MyObject{ customer_id= "101", first_name= "Nichelle",  last_name= "Howell",  phone= "NULL",  email= "nichelle.howell@aol.com",  street= "7670 Forest St.",  city= "Scarsdale",  state= "NY",  zip_code= "10583 "},  
                new MyObject{ customer_id= "102", first_name= "Marisol",  last_name= "Goodman",  phone= "NULL",  email= "marisol.goodman@gmail.com",  street= "864 East Cherry St.",  city= "Canandaigua",  state= "NY",  zip_code= "14424 "},  
                new MyObject{ customer_id= "103", first_name= "Sylvie",  last_name= "Wilkerson",  phone= "NULL",  email= "sylvie.wilkerson@yahoo.com",  street= "750 Central Ave.",  city= "Syosset",  state= "NY",  zip_code= "11791 "},  
                new MyObject{ customer_id= "104", first_name= "Katharina",  last_name= "Bates",  phone= "NULL",  email= "katharina.bates@gmail.com",  street= "54 South Greenview Drive",  city= "Campbell",  state= "CA",  zip_code= "95008 "},  
                new MyObject{ customer_id= "105", first_name= "Marget",  last_name= "Hodge",  phone= "NULL",  email= "marget.hodge@msn.com",  street= "7199 Selby Lane",  city= "Woodhaven",  state= "NY",  zip_code= "11421 "},  
                new MyObject{ customer_id= "106", first_name= "Raul",  last_name= "Melendez",  phone= "NULL",  email= "raul.melendez@hotmail.com",  street= "9772 Manhattan St.",  city= "Elmhurst",  state= "NY",  zip_code= "11373 "},  
                new MyObject{ customer_id= "107", first_name= "Cecil",  last_name= "Hopper",  phone= "NULL",  email= "cecil.hopper@yahoo.com",  street= "471 Glenlake Ave.",  city= "Central Islip",  state= "NY",  zip_code= "11722 "},  
                new MyObject{ customer_id= "108", first_name= "Shae",  last_name= "Hickman",  phone= "NULL",  email= "shae.hickman@hotmail.com",  street= "740 Pin Oak Street",  city= "Floral Park",  state= "NY",  zip_code= "11001 "},  
                new MyObject{ customer_id= "109", first_name= "Monica",  last_name= "Sears",  phone= "(408) 704-8863",  email= "monica.sears@aol.com",  street= "57 Glenholme St.",  city= "San Jose",  state= "CA",  zip_code= "95127 "},  
                new MyObject{ customer_id= "110", first_name= "Ollie",  last_name= "Zimmerman",  phone= "(657) 648-2863",  email= "ollie.zimmerman@yahoo.com",  street= "69 Wood Rd.",  city= "Anaheim",  state= "CA",  zip_code= "92806 "},  
                new MyObject{ customer_id= "111", first_name= "Shila",  last_name= "White",  phone= "NULL",  email= "shila.white@msn.com",  street= "94 Lakeshore Street",  city= "Orchard Park",  state= "NY",  zip_code= "14127 "},  
                new MyObject{ customer_id= "112", first_name= "Yuk",  last_name= "Vega",  phone= "NULL",  email= "yuk.vega@yahoo.com",  street= "413 Wood St.",  city= "West Hempstead",  state= "NY",  zip_code= "11552 "},  
                new MyObject{ customer_id= "113", first_name= "Eliana",  last_name= "Silva",  phone= "NULL",  email= "eliana.silva@gmail.com",  street= "7119 Summer Rd.",  city= "Farmingdale",  state= "NY",  zip_code= "11735 "},  
                new MyObject{ customer_id= "114", first_name= "Thalia",  last_name= "Horne",  phone= "NULL",  email= "thalia.horne@yahoo.com",  street= "9312 Harvard Street",  city= "Amityville",  state= "NY",  zip_code= "11701 "},  
                new MyObject{ customer_id= "115", first_name= "Rey",  last_name= "Lindsay",  phone= "NULL",  email= "rey.lindsay@gmail.com",  street= "16 Philmont St.",  city= "Monroe",  state= "NY",  zip_code= "10950 "},  
                new MyObject{ customer_id= "116", first_name= "Merlene",  last_name= "Vinson",  phone= "NULL",  email= "merlene.vinson@gmail.com",  street= "431 Vine Dr.",  city= "Euless",  state= "TX",  zip_code= "76039 "},  
                new MyObject{ customer_id= "117", first_name= "Dacia",  last_name= "William",  phone= "NULL",  email= "dacia.william@msn.com",  street= "62 Cypress Drive",  city= "Sugar Land",  state= "TX",  zip_code= "77478 "},  
                new MyObject{ customer_id= "118", first_name= "Le",  last_name= "Wood",  phone= "NULL",  email= "le.wood@yahoo.com",  street= "90 Primrose Dr.",  city= "Pittsford",  state= "NY",  zip_code= "14534 "},  
                new MyObject{ customer_id= "119", first_name= "Thalia",  last_name= "Dillard",  phone= "NULL",  email= "thalia.dillard@yahoo.com",  street= "987 NE. Gates Street",  city= "San Angelo",  state= "TX",  zip_code= "76901 "},  
                new MyObject{ customer_id= "120", first_name= "Luz",  last_name= "House",  phone= "(559) 114-2580",  email= "luz.house@gmail.com",  street= "491 Railroad Street",  city= "Fresno",  state= "CA",  zip_code= "93706 "},  
                new MyObject{ customer_id= "121", first_name= "Lucy",  last_name= "Woods",  phone= "NULL",  email= "lucy.woods@gmail.com",  street= "8437 West Rockaway St.",  city= "Palos Verdes Peninsula",  state= "CA",  zip_code= "90274 "},  
                new MyObject{ customer_id= "122", first_name= "Shena",  last_name= "Carter",  phone= "NULL",  email= "shena.carter@yahoo.com",  street= "72 University Road",  city= "Howard Beach",  state= "NY",  zip_code= "11414 "},  
                new MyObject{ customer_id= "123", first_name= "Robena",  last_name= "Hill",  phone= "(361) 598-4414",  email= "robena.hill@hotmail.com",  street= "263 Cross St.",  city= "Corpus Christi",  state= "TX",  zip_code= "78418 "},  
                new MyObject{ customer_id= "124", first_name= "Jeni",  last_name= "Booker",  phone= "NULL",  email= "jeni.booker@gmail.com",  street= "546 Railroad Dr.",  city= "South El Monte",  state= "CA",  zip_code= "91733 "},  
                new MyObject{ customer_id= "125", first_name= "Herlinda",  last_name= "Stone",  phone= "NULL",  email= "herlinda.stone@msn.com",  street= "725 Gulf St.",  city= "Canandaigua",  state= "NY",  zip_code= "14424 "},  
                new MyObject{ customer_id= "126", first_name= "Lavina",  last_name= "Dejesus",  phone= "NULL",  email= "lavina.dejesus@msn.com",  street= "59 E. Valley Avenue",  city= "Newburgh",  state= "NY",  zip_code= "12550 "},  
                new MyObject{ customer_id= "127", first_name= "Erlinda",  last_name= "Nielsen",  phone= "NULL",  email= "erlinda.nielsen@aol.com",  street= "728 Oxford Lane",  city= "Maspeth",  state= "NY",  zip_code= "11378 "},  
                new MyObject{ customer_id= "128", first_name= "Terrance",  last_name= "Lynn",  phone= "NULL",  email= "terrance.lynn@yahoo.com",  street= "91 East Buckingham Drive",  city= "Plattsburgh",  state= "NY",  zip_code= "12901 "},  
                new MyObject{ customer_id= "129", first_name= "Walton",  last_name= "Dejesus",  phone= "NULL",  email= "walton.dejesus@yahoo.com",  street= "15 Washington Rd.",  city= "Lockport",  state= "NY",  zip_code= "14094 "},  
                new MyObject{ customer_id= "130", first_name= "Wes",  last_name= "Stanton",  phone= "(248) 247-5074",  email= "wes.stanton@msn.com",  street= "8662 Tunnel Street",  city= "Troy",  state= "NY",  zip_code= "12180 "},  
                new MyObject{ customer_id= "131", first_name= "Tanesha",  last_name= "Hampton",  phone= "NULL",  email= "tanesha.hampton@hotmail.com",  street= "19 Belmont Ave.",  city= "Syosset",  state= "NY",  zip_code= "11791 "},  
                new MyObject{ customer_id= "132", first_name= "Boyd",  last_name= "Irwin",  phone= "NULL",  email= "boyd.irwin@hotmail.com",  street= "221 Whitemarsh St.",  city= "Hamburg",  state= "NY",  zip_code= "14075 "},  
                new MyObject{ customer_id= "133", first_name= "Delbert",  last_name= "Wilkins",  phone= "NULL",  email= "delbert.wilkins@aol.com",  street= "420 Greenview St.",  city= "Coram",  state= "NY",  zip_code= "11727 "},  
                new MyObject{ customer_id= "134", first_name= "Brianna",  last_name= "Moss",  phone= "(516) 156-8031",  email= "brianna.moss@msn.com",  street= "4 Longfellow St.",  city= "Hempstead",  state= "NY",  zip_code= "11550 "},  
                new MyObject{ customer_id= "135", first_name= "Dorthey",  last_name= "Jackson",  phone= "(281) 926-8010",  email= "dorthey.jackson@msn.com",  street= "9768 Brookside St.",  city= "Houston",  state= "TX",  zip_code= "77016 "},  
                new MyObject{ customer_id= "136", first_name= "Sarita",  last_name= "Parks",  phone= "NULL",  email= "sarita.parks@msn.com",  street= "7809 Second Lane",  city= "Forney",  state= "TX",  zip_code= "75126 "},  
                new MyObject{ customer_id= "137", first_name= "Shonta",  last_name= "Mercer",  phone= "NULL",  email= "shonta.mercer@aol.com",  street= "319 NE. La Sierra Avenue",  city= "Massapequa",  state= "NY",  zip_code= "11758 "},  
                new MyObject{ customer_id= "138", first_name= "Jone",  last_name= "Bernard",  phone= "(657) 536-5165",  email= "jone.bernard@hotmail.com",  street= "99 Longbranch Court",  city= "Anaheim",  state= "CA",  zip_code= "92806 "},  
                new MyObject{ customer_id= "139", first_name= "Wanita",  last_name= "Davenport",  phone= "NULL",  email= "wanita.davenport@aol.com",  street= "525 Dogwood Ave.",  city= "Spring Valley",  state= "NY",  zip_code= "10977 "},  
                new MyObject{ customer_id= "140", first_name= "Cleopatra",  last_name= "Tate",  phone= "NULL",  email= "cleopatra.tate@aol.com",  street= "97 N. Glenwood St.",  city= "East Elmhurst",  state= "NY",  zip_code= "11369 "},  
                new MyObject{ customer_id= "141", first_name= "Ramiro",  last_name= "Byers",  phone= "NULL",  email= "ramiro.byers@gmail.com",  street= "16 Pleasant St.",  city= "Saint Albans",  state= "NY",  zip_code= "11412 "},  
                new MyObject{ customer_id= "142", first_name= "Nicholas",  last_name= "Vazquez",  phone= "NULL",  email= "nicholas.vazquez@hotmail.com",  street= "9 Roosevelt Street",  city= "West Hempstead",  state= "NY",  zip_code= "11552 "},  
                new MyObject{ customer_id= "143", first_name= "Janae",  last_name= "Doyle",  phone= "NULL",  email= "janae.doyle@gmail.com",  street= "760 Rose Ave.",  city= "Jackson Heights",  state= "NY",  zip_code= "11372 "},  
                new MyObject{ customer_id= "144", first_name= "Hans",  last_name= "Price",  phone= "NULL",  email= "hans.price@hotmail.com",  street= "51 Glendale Road",  city= "Port Chester",  state= "NY",  zip_code= "10573 "},  
                new MyObject{ customer_id= "145", first_name= "Miquel",  last_name= "Neal",  phone= "NULL",  email= "miquel.neal@hotmail.com",  street= "9564 Deerfield Lane",  city= "Staten Island",  state= "NY",  zip_code= "10301 "},  
                new MyObject{ customer_id= "146", first_name= "Stefany",  last_name= "Potter",  phone= "NULL",  email= "stefany.potter@gmail.com",  street= "256 South Academy St.",  city= "Saratoga Springs",  state= "NY",  zip_code= "12866 "},  
                new MyObject{ customer_id= "147", first_name= "Bernetta",  last_name= "Marquez",  phone= "NULL",  email= "bernetta.marquez@hotmail.com",  street= "626 E. Dunbar Street",  city= "Smithtown",  state= "NY",  zip_code= "11787 "},  
                new MyObject{ customer_id= "148", first_name= "Julee",  last_name= "Woodard",  phone= "NULL",  email= "julee.woodard@yahoo.com",  street= "869 Summerhouse Dr.",  city= "Richmond Hill",  state= "NY",  zip_code= "11418 "},  
                new MyObject{ customer_id= "149", first_name= "Meredith",  last_name= "Bryan",  phone= "NULL",  email= "meredith.bryan@hotmail.com",  street= "8935 E. Oxford St.",  city= "Spring Valley",  state= "NY",  zip_code= "10977 "},  
                new MyObject{ customer_id= "150", first_name= "Weldon",  last_name= "Michael",  phone= "NULL",  email= "weldon.michael@hotmail.com",  street= "9952 Nut Swamp St.",  city= "Huntington",  state= "NY",  zip_code= "11743 "},  
                new MyObject{ customer_id= "151", first_name= "Joesph",  last_name= "Delacruz",  phone= "NULL",  email= "joesph.delacruz@aol.com",  street= "184 Cypress Street",  city= "Atwater",  state= "CA",  zip_code= "95301 "},  
                new MyObject{ customer_id= "152", first_name= "Katherina",  last_name= "Odom",  phone= "NULL",  email= "katherina.odom@yahoo.com",  street= "897 N. Oak Drive",  city= "Plainview",  state= "NY",  zip_code= "11803 "},  
                new MyObject{ customer_id= "153", first_name= "Laraine",  last_name= "Robbins",  phone= "NULL",  email= "laraine.robbins@yahoo.com",  street= "8214 E. Pin Oak Lane",  city= "San Angelo",  state= "TX",  zip_code= "76901 "},  
                new MyObject{ customer_id= "154", first_name= "Jenise",  last_name= "Preston",  phone= "NULL",  email= "jenise.preston@yahoo.com",  street= "9 Littleton Drive",  city= "Helotes",  state= "TX",  zip_code= "78023 "},  
                new MyObject{ customer_id= "155", first_name= "Lory",  last_name= "Page",  phone= "NULL",  email= "lory.page@hotmail.com",  street= "58 Summerhouse Street",  city= "Bay Shore",  state= "NY",  zip_code= "11706 "},  
                new MyObject{ customer_id= "156", first_name= "Charlyn",  last_name= "Cantrell",  phone= "NULL",  email= "charlyn.cantrell@yahoo.com",  street= "8756 Euclid St.",  city= "West Islip",  state= "NY",  zip_code= "11795 "},  
                new MyObject{ customer_id= "157", first_name= "Carola",  last_name= "Rodriquez",  phone= "NULL",  email= "carola.rodriquez@hotmail.com",  street= "9433 Heritage Lane",  city= "Banning",  state= "CA",  zip_code= "92220 "},  
                new MyObject{ customer_id= "158", first_name= "Alane",  last_name= "Kennedy",  phone= "NULL",  email= "alane.kennedy@yahoo.com",  street= "34 Green Lake Street",  city= "Spring Valley",  state= "NY",  zip_code= "10977 "},  
                new MyObject{ customer_id= "159", first_name= "Regina",  last_name= "Burns",  phone= "NULL",  email= "regina.burns@aol.com",  street= "713 Buckingham St.",  city= "Garland",  state= "TX",  zip_code= "75043 "},  
                new MyObject{ customer_id= "160", first_name= "Omer",  last_name= "Estrada",  phone= "NULL",  email= "omer.estrada@gmail.com",  street= "9 Honey Creek Street",  city= "Rowlett",  state= "TX",  zip_code= "75088 "},  
                new MyObject{ customer_id= "161", first_name= "Crystle",  last_name= "Gilliam",  phone= "NULL",  email= "crystle.gilliam@yahoo.com",  street= "86 Edgewater Road",  city= "Smithtown",  state= "NY",  zip_code= "11787 "},  
                new MyObject{ customer_id= "162", first_name= "Kam",  last_name= "Wilder",  phone= "NULL",  email= "kam.wilder@hotmail.com",  street= "500 West Clay Ave.",  city= "Newburgh",  state= "NY",  zip_code= "12550 "},  
                new MyObject{ customer_id= "163", first_name= "Margert",  last_name= "Stevens",  phone= "NULL",  email= "margert.stevens@aol.com",  street= "502 North Poplar St.",  city= "Rome",  state= "NY",  zip_code= "13440 "},  
                new MyObject{ customer_id= "164", first_name= "Tomika",  last_name= "Larson",  phone= "NULL",  email= "tomika.larson@yahoo.com",  street= "254 Canal St.",  city= "Woodside",  state= "NY",  zip_code= "11377 "},  
                new MyObject{ customer_id= "165", first_name= "Jeromy",  last_name= "Burch",  phone= "(408) 955-8238",  email= "jeromy.burch@msn.com",  street= "889 Mulberry Street",  city= "San Jose",  state= "CA",  zip_code= "95127 "},  
                new MyObject{ customer_id= "166", first_name= "Lena",  last_name= "Mills",  phone= "NULL",  email= "lena.mills@yahoo.com",  street= "42 Homestead St.",  city= "Woodhaven",  state= "NY",  zip_code= "11421 "},  
                new MyObject{ customer_id= "167", first_name= "Loreta",  last_name= "Johnston",  phone= "NULL",  email= "loreta.johnston@yahoo.com",  street= "39 Lafayette Dr.",  city= "Spring Valley",  state= "NY",  zip_code= "10977 "},  
                new MyObject{ customer_id= "168", first_name= "Nettie",  last_name= "Mcdaniel",  phone= "NULL",  email= "nettie.mcdaniel@hotmail.com",  street= "7004 E. Wakehurst St.",  city= "South Ozone Park",  state= "NY",  zip_code= "11420 "},  
                new MyObject{ customer_id= "169", first_name= "Karla",  last_name= "Kirk",  phone= "NULL",  email= "karla.kirk@yahoo.com",  street= "9718 Harvard Rd.",  city= "Palos Verdes Peninsula",  state= "CA",  zip_code= "90274 "},  
                new MyObject{ customer_id= "170", first_name= "Regine",  last_name= "Gonzales",  phone= "(805) 763-4045",  email= "regine.gonzales@gmail.com",  street= "798 Court Drive",  city= "Oxnard",  state= "CA",  zip_code= "93035 "},  
                new MyObject{ customer_id= "171", first_name= "Miriam",  last_name= "Baker",  phone= "NULL",  email= "miriam.baker@hotmail.com",  street= "90 Studebaker St.",  city= "Uniondale",  state= "NY",  zip_code= "11553 "},  
                new MyObject{ customer_id= "172", first_name= "Jeanie",  last_name= "Kirkland",  phone= "NULL",  email= "jeanie.kirkland@aol.com",  street= "7643 Old Theatre St.",  city= "Santa Clara",  state= "CA",  zip_code= "95050 "},  
                new MyObject{ customer_id= "173", first_name= "Marquerite",  last_name= "Dawson",  phone= "NULL",  email= "marquerite.dawson@gmail.com",  street= "37 Hamilton Court",  city= "Garland",  state= "TX",  zip_code= "75043 "},  
                new MyObject{ customer_id= "174", first_name= "Babara",  last_name= "Ochoa",  phone= "NULL",  email= "babara.ochoa@aol.com",  street= "872 Smith Store St.",  city= "Scarsdale",  state= "NY",  zip_code= "10583 "},  
                new MyObject{ customer_id= "175", first_name= "Nova",  last_name= "Hess",  phone= "NULL",  email= "nova.hess@msn.com",  street= "773 South Lafayette St.",  city= "Duarte",  state= "CA",  zip_code= "91010 "},  
                new MyObject{ customer_id= "176", first_name= "Carley",  last_name= "Reynolds",  phone= "NULL",  email= "carley.reynolds@gmail.com",  street= "2 Snake Hill Drive",  city= "South El Monte",  state= "CA",  zip_code= "91733 "},  
                new MyObject{ customer_id= "177", first_name= "Carissa",  last_name= "Foreman",  phone= "NULL",  email= "carissa.foreman@msn.com",  street= "69C N. Ridge Rd.",  city= "Maspeth",  state= "NY",  zip_code= "11378 "},  
                new MyObject{ customer_id= "178", first_name= "Genoveva",  last_name= "Tyler",  phone= "(212) 152-6381",  email= "genoveva.tyler@gmail.com",  street= "8121 Windfall Ave.",  city= "New York",  state= "NY",  zip_code= "10002 "},  
                new MyObject{ customer_id= "179", first_name= "Deane",  last_name= "Sears",  phone= "NULL",  email= "deane.sears@hotmail.com",  street= "3 Bradford Court",  city= "Pittsford",  state= "NY",  zip_code= "14534 "},  
                new MyObject{ customer_id= "180", first_name= "Karey",  last_name= "Steele",  phone= "NULL",  email= "karey.steele@gmail.com",  street= "8879 Kent Lane",  city= "Farmingdale",  state= "NY",  zip_code= "11735 "},  
                new MyObject{ customer_id= "181", first_name= "Olevia",  last_name= "Pitts",  phone= "NULL",  email= "olevia.pitts@gmail.com",  street= "39 Fieldstone Drive",  city= "Redondo Beach",  state= "CA",  zip_code= "90278 "},  
                new MyObject{ customer_id= "182", first_name= "Jenniffer",  last_name= "Bullock",  phone= "NULL",  email= "jenniffer.bullock@msn.com",  street= "38 Oxford Avenue",  city= "Bay Shore",  state= "NY",  zip_code= "11706 "},  
                new MyObject{ customer_id= "183", first_name= "Jeniffer",  last_name= "Ratliff",  phone= "NULL",  email= "jeniffer.ratliff@gmail.com",  street= "510 Rocky River Court",  city= "Floral Park",  state= "NY",  zip_code= "11001 "},  
                new MyObject{ customer_id= "184", first_name= "Klara",  last_name= "Stanley",  phone= "NULL",  email= "klara.stanley@aol.com",  street= "603 Mechanic St.",  city= "Webster",  state= "NY",  zip_code= "14580 "},  
                new MyObject{ customer_id= "185", first_name= "Morton",  last_name= "Lee",  phone= "NULL",  email= "morton.lee@yahoo.com",  street= "313 Ridge St.",  city= "San Angelo",  state= "TX",  zip_code= "76901 "},  
                new MyObject{ customer_id= "186", first_name= "Ken",  last_name= "Charles",  phone= "NULL",  email= "ken.charles@msn.com",  street= "9124 W. Piper Lane",  city= "Monsey",  state= "NY",  zip_code= "10952 "},  
                new MyObject{ customer_id= "187", first_name= "Hedwig",  last_name= "Paul",  phone= "NULL",  email= "hedwig.paul@msn.com",  street= "422 Manor Ave.",  city= "Apple Valley",  state= "CA",  zip_code= "92307 "},  
                new MyObject{ customer_id= "188", first_name= "Sharla",  last_name= "Flynn",  phone= "(805) 478-7724",  email= "sharla.flynn@hotmail.com",  street= "7 Brown Drive",  city= "Oxnard",  state= "CA",  zip_code= "93035 "},  
                new MyObject{ customer_id= "189", first_name= "Damian",  last_name= "Dawson",  phone= "NULL",  email= "damian.dawson@hotmail.com",  street= "528 St Margarets Street",  city= "Liverpool",  state= "NY",  zip_code= "13090 "},  
                new MyObject{ customer_id= "190", first_name= "Toya",  last_name= "Pratt",  phone= "(562) 218-6405",  email= "toya.pratt@yahoo.com",  street= "485 San Pablo Drive",  city= "Long Beach",  state= "NY",  zip_code= "11561 "},  
                new MyObject{ customer_id= "191", first_name= "Graciela",  last_name= "Barber",  phone= "(805) 656-6987",  email= "graciela.barber@hotmail.com",  street= "1 E. Young St.",  city= "Oxnard",  state= "CA",  zip_code= "93035 "},  
                new MyObject{ customer_id= "192", first_name= "Bong",  last_name= "Hebert",  phone= "NULL",  email= "bong.hebert@gmail.com",  street= "545 Brook St.",  city= "Torrance",  state= "CA",  zip_code= "90505 "},  
                new MyObject{ customer_id= "193", first_name= "Ayanna",  last_name= "Rhodes",  phone= "NULL",  email= "ayanna.rhodes@msn.com",  street= "7425 Pheasant St.",  city= "Hicksville",  state= "NY",  zip_code= "11801 "},  
                new MyObject{ customer_id= "194", first_name= "Dorine",  last_name= "Roberson",  phone= "NULL",  email= "dorine.roberson@msn.com",  street= "396 Meadowbrook Lane",  city= "Santa Cruz",  state= "CA",  zip_code= "95060 "},  
                new MyObject{ customer_id= "195", first_name= "Addie",  last_name= "Hahn",  phone= "NULL",  email= "addie.hahn@hotmail.com",  street= "8165 Baker Ave.",  city= "Franklin Square",  state= "NY",  zip_code= "11010 "},  
                new MyObject{ customer_id= "196", first_name= "Edythe",  last_name= "Valencia",  phone= "NULL",  email= "edythe.valencia@yahoo.com",  street= "9346 Wall St.",  city= "North Tonawanda",  state= "NY",  zip_code= "14120 "},  
                new MyObject{ customer_id= "197", first_name= "Andy",  last_name= "O'neill",  phone= "NULL",  email= "andy.o'neill@msn.com",  street= "9544 Mulberry Drive",  city= "Rego Park",  state= "NY",  zip_code= "11374 "},  
                new MyObject{ customer_id= "198", first_name= "Luis",  last_name= "Tyler",  phone= "NULL",  email= "luis.tyler@gmail.com",  street= "9568 Campfire Circle",  city= "Amarillo",  state= "TX",  zip_code= "79106 "},  
                new MyObject{ customer_id= "199", first_name= "Clelia",  last_name= "Workman",  phone= "NULL",  email= "clelia.workman@yahoo.com",  street= "620 North Somerset St.",  city= "New Windsor",  state= "NY",  zip_code= "12553 "},  
                new MyObject{ customer_id= "200", first_name= "Ashely",  last_name= "Holmes",  phone= "NULL",  email= "ashely.holmes@aol.com",  street= "45 High Ridge Ave.",  city= "Farmingdale",  state= "NY",  zip_code= "11735" }

            };


            string responseMessage = string.IsNullOrEmpty(name)
            return new OkObjectResult(responseMessage);
        }
    }
}
